#!/bin/bash
#
# ScreenInvader - A shared media experience. Instant and seamless.
#  Copyright (C) 2012 Amir Hassan <amir@viel-zu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

COMMAND="$1"
BEAMER_SERIAL_DEVICE="/dev/benq"

#echo >> /tmp/send_command
#set >> /tmp/send_command 
#echo "send_command: ${COMMAND}" >> /tmp/send_command

# initialize every time for now
stty -ixoff -parenb cs8 -cstopb -F ${BEAMER_SERIAL_DEVICE} 9600

# send the command (see ftp://supportfiles.benq.eu/projector/benq_rs232_commands.pdf)
#echo -e "\r*${COMMAND}#\r" > ${BEAMER_SERIAL_DEVICE} 2> /dev/null
echo -e "\r*${COMMAND}#\r" > ${BEAMER_SERIAL_DEVICE} 

exit $?
